name: Deploy Express to OCI - 20 Jul, 2026

on:
  push:
    branches:
      - main

jobs:
  checkout:
    name: Checkout Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  deploy-by-im:
    name: Deploy via SSH
    runs-on: ubuntu-latest
    needs: checkout

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/${{ secrets.SSH_USERNAME }}/v3-git-actions-20j26
            git pull
            docker compose up -d --build
