name: Deploy Express to OCI - 20 Jul, 2026

on:
  push:
    branches:
      - main

jobs:
  deploy-by-im:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd /home/${{ secrets.SSH_USERNAME }}/v3-git-actions-20j26
            git pull
            docker compose up -d --build

# =============================================
    # runs-on: ubuntu-latest

    # steps:
    #   - name: Checkout code
    #     uses: actions/checkout@v4

    #   - name: Deploy to OCI via SSH
    #     uses: appleboy/ssh-action@v1.0.3
    #     with:
    #       # host: ${{ secrets.SSH_HOST }}
    #       host: 145.241.159.52
    #       username: ${{ secrets.SSH_USERNAME }}
    #       key: ${{ secrets.PRIVATE_KEY }}
    #       # port: ${{ secrets.SSH_PORT }}
    #       port: 22
    #       script: |
    #         set -e

    #         echo "Current user:"
    #         whoami

    #         echo "Current directory:"
    #         pwd

    #         cd /home/${{ secrets.SSH_USERNAME }}/git-actions-test

    #         echo "Current directory after cd:"
    #         pwd

    #         echo "Repository status:"
    #         git status

    #         echo "Current branch:"
    #         git branch

    #         echo "Fetching origin..."
    #         git fetch origin
    #         git checkout ${{ github.ref_name }}
    #         git pull origin ${{ github.ref_name }}
            
    #         docker compose up -d --build
